const API='https://recovery.nexhavenos.com/api/rental/';
const $p=s=>document.querySelector(s), html=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let auditId='',accessToken='',previewState=null;
function error(message){$p('#preview-error').textContent=message;$p('#preview-error').hidden=false;}
function clearError(){$p('#preview-error').hidden=true;}
async function api(path,body,method){const r=await fetch(API+path,{method:method||(body?'POST':'GET'),headers:{...(body?{'Content-Type':'application/json'}:{}),...(accessToken?{Authorization:'Bearer '+accessToken}:{})},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(35000)});let j;try{j=await r.json();}catch{throw new Error('The preview service did not respond correctly. Please try again.');}if(!r.ok)throw new Error(j.error||'Unable to complete request.');return j;}
async function busy(button,fn){if(button.disabled)return;const label=button.textContent;button.disabled=true;button.textContent='Working…';clearError();try{await fn();}catch(e){error(e.name==='TimeoutError'?'The request took too long. Please try again.':e.message);}finally{button.disabled=false;button.textContent=label;}}
function validLink(url){try{const u=new URL(url);return u.protocol==='https:'?u.href:null;}catch{return null;}}
function sourceLink(url){const u=validLink(url);return u?`<a class="finding-source" href="${html(u)}" target="_blank" rel="noreferrer">Public source ↗</a>`:'';}
function findings(items,empty){return items?.length?items.map(x=>`<h3>${html(x.title)}</h3><p>${html(x.detail)}</p>${sourceLink(x.source)}`).join(''):`<p>${html(empty)}</p>`;}
function render(state){previewState=state;const p=state.preview;$p('#results-section').hidden=false;$p('#result-title').textContent=p.title||'Your property preview';$p('#result-address').textContent=state.address;$p('#result-method').textContent=p.method||'';$p('#checked-at').textContent='Source check: '+new Date(p.checkedAt).toLocaleString();$p('#property-facts').innerHTML=(p.facts||[]).map(f=>`<div class="fact"><b>${html(f.label)}</b><span>${html(f.value)}</span>${sourceLink(f.source)}</div>`).join('');$p('#findings-good').innerHTML=findings(p.good,'No property strengths were verified from the available sources. This is a data gap, not a negative rating.');$p('#findings-improve').innerHTML=findings(p.improve,'No source-backed improvement finding is available yet. A closer source review is needed.');$p('#findings-unknown').innerHTML=(p.unknown||[]).map(t=>`<p>${html(t)}</p>`).join('');$p('#audit-terms').textContent=state.terms||'';$p('#audit-price').innerHTML=state.reportReady?`$${Number(state.priceCents/100).toLocaleString()} <small>one-time confirmed audit fee</small>`:'$497–$997 <small>one-time · confirmed before payment</small>';
 const button=$p('#checkout-button');button.disabled=!state.checkoutEnabled&&!state.paid;button.textContent=state.paid?'Open my full audit':state.checkoutEnabled?'Pay to unlock my full audit':'Full audit not yet available';$p('#terms-control').hidden=!state.checkoutEnabled||state.paid;
 $p('#payment-status').textContent=state.paid?'Payment confirmed. Your full audit is available.':state.reportReady?(state.checkoutEnabled?'Your report is ready. Review the scope and terms before paying.':'Your report is ready. Online payment is not yet available; no charge has been taken.'):'Your preview is free. The full report and scope must be ready before checkout. Online payments are not yet available.';
 if(state.contactSaved)$p('#contact-status').textContent='Your audit request is saved. Keep your private preview link.';
}
$p('#lookup-form').addEventListener('submit',e=>{e.preventDefault();busy(e.target.querySelector('[type=submit]'),async()=>{const result=await api('lookup',{address:$p('#property-address').value});$p('#lookup-status').textContent=result.notice||'';if(!result.matches?.length){$p('#confirm-section').hidden=true;return;}$p('#confirm-section').hidden=false;$p('#discovery-notice').textContent=result.notice;$p('#address-match').innerHTML=result.matches.map(m=>`<option>${html(m.address)}</option>`).join('');$p('#source-candidates').innerHTML=(result.candidates||[]).map((c,i)=>`<button type="button" data-source="${i}">${html(c.title)}<small>${html(c.kind)} · ${html(c.url)}</small></button>`).join('');$p('#source-candidates').querySelectorAll('[data-source]').forEach(b=>b.onclick=()=>{$p('#property-source').value=result.candidates[Number(b.dataset.source)].url;$p('#confirm-property').checked=false;});$p('#confirm-property').checked=false;$p('#confirm-section').scrollIntoView({behavior:'smooth',block:'start'});});});
$p('#confirm-form').addEventListener('submit',e=>{e.preventDefault();busy(e.target.querySelector('[type=submit]'),async()=>{const result=await api('preview',{address:$p('#address-match').value,listingUrl:$p('#property-source').value,confirmed:$p('#confirm-property').checked});auditId=result.id;accessToken=result.token;history.replaceState(null,'',location.pathname+location.search+'#'+auditId+'.'+accessToken);render(result);$p('#results-section').scrollIntoView({behavior:'smooth',block:'start'});});});
$p('#preview-contact').addEventListener('submit',e=>{e.preventDefault();busy(e.target.querySelector('[type=submit]'),async()=>{const r=await api('contact/'+auditId,{name:$p('#preview-name').value,email:$p('#preview-email').value,consent:$p('#preview-consent').checked});$p('#contact-status').textContent=r.message;previewState.contactSaved=true;});});
async function report(){const r=await api('report/'+auditId);const labels={summary:'Executive summary',listing:'Listing',pricing:'Pricing',comps:'Comparable properties',photos:'Photos',minimumStays:'Minimum stays',amenities:'Amenities',reviews:'Reviews',directBookings:'Direct bookings',leakage:'Estimated leakage and assumptions',plan30:'30-day plan'};$p('#full-report-content').innerHTML=Object.entries(labels).map(([k,v])=>`<section class="report-section"><h3>${v}</h3><p>${html(r.report[k])}</p></section>`).join('')+'<h3>Sources</h3>'+r.report.sources.map(sourceLink).join('');$p('#full-report').hidden=false;$p('#full-report').scrollIntoView({behavior:'smooth'});}
$p('#checkout-button').addEventListener('click',()=>busy($p('#checkout-button'),async()=>{if(previewState?.paid)return report();if(!$p('#accept-terms').checked)throw new Error('Please accept the displayed scope and terms first.');const r=await api('checkout/'+auditId,{acceptedTerms:true});if(r.paid){render(await api('status/'+auditId));return report();}const u=new URL(r.url);if(u.protocol!=='https:'||u.hostname!=='checkout.stripe.com')throw new Error('Checkout could not be opened safely. Please contact NexHaven.');location.assign(u.href);}));
$p('#refresh-report').addEventListener('click',()=>busy($p('#refresh-report'),async()=>{render(await api('status/'+auditId));if(previewState.paid)await report();}));
$p('#copy-preview').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);$p('#link-status').textContent='Private link copied. Keep it somewhere secure.';}catch{$p('#link-status').textContent='Copy this page’s address from your browser and keep it secure.';}};
const fragment=location.hash.slice(1).split('.');if(fragment.length===2&&/^[a-f0-9-]{36}$/.test(fragment[0])&&/^[a-f0-9-]{72}$/.test(fragment[1])){[auditId,accessToken]=fragment;api('status/'+auditId).then(async state=>{render(state);if(new URLSearchParams(location.search).get('payment')==='return'){try{await report();render(await api('status/'+auditId));}catch(e){error(e.message);}}}).catch(e=>error(e.message));}

